import { Footer, Header } from "#/components/common";
import { Breadcrumbs } from "#/components/UI";
import "#/styles/globals.css";
import { Montserrat } from "next/font/google";
import styles from "./styles.module.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const primaryFont = Montserrat({
	weight: ["300", "400", "600"],
	subsets: ["latin"],
	variable: "--primary-font",
	style: "normal"
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html className={`${primaryFont.variable}`} lang='en'>
			<body>
				<div className={styles.wrapper}>
					<Header />
					<Breadcrumbs />
					<main className={styles.page}>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
